# Generated by Django 2.0 on 2018-01-24 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0008_responsetoactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity')),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activity.ResponseToActivity')),
            ],
        ),
    ]
