# Generated by Django 2.0 on 2018-02-02 19:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20180202_1948'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='response',
        ),
        migrations.AddField(
            model_name='contract',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='activity.OfferToActivity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='scheduled_for',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 2, 19, 48, 30, 362781, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
