# Generated by Django 2.0 on 2018-01-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_id',
            field=models.TextField(blank=True),
        ),
    ]
