# Generated by Django 2.0 on 2018-01-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
