# Generated by Django 2.0 on 2018-02-08 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180202_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingdemand',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='ratingdemand',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating_demand',
        ),
        migrations.DeleteModel(
            name='RatingDemand',
        ),
    ]
