# Generated by Django 2.0 on 2018-02-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180208_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating_supply',
            field=models.IntegerField(default=0),
        ),
    ]
