# Generated by Django 2.0 on 2017-12-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.ManyToManyField(blank=True, to='activity.Category'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ManyToManyField(blank=True, to='utils.Image'),
        ),
    ]
