# Generated by Django 2.0 on 2017-12-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20171227_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type_activity',
            field=models.CharField(choices=[('SU', 'Supply'), ('DE', 'Demand')], max_length=2),
        ),
    ]
