# Generated by Django 2.0 on 2018-01-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_responsetoactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsetoactivity',
            name='price',
        ),
    ]
