# Generated by Django 2.0 on 2018-02-02 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0009_remove_responsetoactivity_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferToActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('OP', 'Abierta'), ('PE', 'Pendiente'), ('DO', 'Realizada'), ('pe', 'Cancelada')], default='OP', max_length=2),
        ),
        migrations.AddField(
            model_name='offertoactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='activity.Activity'),
        ),
        migrations.AddField(
            model_name='offertoactivity',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(1), to=settings.AUTH_USER_MODEL),
        ),
    ]
