# Generated by Django 2.0 on 2018-02-05 00:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20180202_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='offertoactivity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offertoactivity',
            name='scheduled_for',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 5, 0, 17, 6, 228797, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
